# Generated by Django 4.1.5 on 2023-01-07 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('house', models.CharField(max_length=255)),
                ('open_at', models.DateTimeField()),
                ('close_at', models.DateTimeField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.city')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.street')),
            ],
        ),
    ]
