# Generated by Django 4.1.5 on 2023-01-08 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_alter_city_options_alter_country_options_and_more'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['name'], 'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='close_at',
            field=models.TimeField(verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='house',
            field=models.CharField(max_length=255, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название магазина'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='open_at',
            field=models.TimeField(verbose_name='Время открытия'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.street', verbose_name='Улица'),
        ),
    ]
